import unittest
from db_test_utils import _banner, _section, _step, _result, _ok, _wal_snapshot, _table_snapshot, fresh_db

class TestAtomicity(unittest.TestCase):

    def test_successful_single_insert_commits(self):
        _banner("ATOMICITY  ·  successful single insert commits")
        _section("Setup")
        db = fresh_db()
        _step("Fresh database created. WAL is empty. Table 'users' has 0 rows.")
        _section("Action: insert key=1  →  {'id':1, 'name':'Alice'}  then COMMIT")
        _step("Step 1 · TransactionManager.begin() assigns txn_id=1, writes BEGIN to WAL.")
        _step("Step 2 · table.transactional_insert() writes INSERT(key=1) to WAL and immediately calls _raw_insert() so the row exists in memory.")
        _step("Step 3 · db_manager.commit() writes COMMIT to WAL then fsyncs to disk.")
        db.insert_record("users", 1, {"id": 1, "name": "Alice"})
        _wal_snapshot(db)
        _section("Verification")
        record = db.get_table("users").search(1)
        _result("search(1) returned", record)
        _result("record['name']", record["name"])
        _table_snapshot(db, "users")
        self.assertIsNotNone(record)
        self.assertEqual(record["name"], "Alice")
        _ok("INSERT committed → row is visible in both records dict and B+ Tree index.")

    def test_rollback_insert_leaves_no_trace(self):
        _banner("ATOMICITY  ·  rollback insert leaves no trace")
        _section("Setup")
        db = fresh_db()
        _step("Fresh database. Table 'users' is empty.")
        _section("Action: begin txn, insert key=99, then ROLLBACK (simulated failure)")
        _step("Step 1 · begin_transaction() → txn_id=1.")
        txn = db.begin_transaction()
        _step("Step 2 · transactional_insert(key=99) stages INSERT in WAL and calls _raw_insert() — row is temporarily in memory.")
        db.get_table("users").transactional_insert(txn, 99, {"id": 99, "name": "Ghost"})
        _step("Step 3 · Before commit, failure detected → db.rollback(txn).")
        _step("         Transaction.abort() iterates _ops in REVERSE and calls _raw_delete(99) to undo the insert. ABORT record written to WAL.")
        db.rollback(txn)
        _wal_snapshot(db)
        _section("Verification")
        search_result = db.get_table("users").search(99)
        in_records    = 99 in db.get_table("users").records
        in_index      = db.get_table("users").bplustree.search(99)
        _result("search(99) after rollback", search_result,  good=(search_result is None))
        _result("key 99 in records dict",    in_records,     good=(not in_records))
        _result("B+ Tree search(99)",        in_index,       good=(in_index is None))
        _table_snapshot(db, "users")
        self.assertIsNone(search_result)
        self.assertNotIn(99, db.get_table("users").records)
        self.assertIsNone(in_index)
        _ok("Rolled-back INSERT left zero trace in the database.")

    def test_rollback_update_restores_old_value(self):
        _banner("ATOMICITY  ·  rollback update restores old value")
        _section("Setup")
        db = fresh_db()
        db.insert_record("users", 2, {"id": 2, "name": "Bob"})
        _step("Committed row: key=2, name='Bob'.")
        _section("Action: update name to 'Robert', then ROLLBACK")
        _step("Step 1 · transactional_update() snapshots BEFORE-IMAGE {'name':'Bob'} into WAL record's old_value field.")
        _step("Step 2 · _raw_update() overwrites record in memory with 'Robert'.")
        txn = db.begin_transaction()
        db.get_table("users").transactional_update(txn, 2, {"id": 2, "name": "Robert"})
        _step("         (record is now 'Robert' in memory — txn NOT yet committed)")
        _step("Step 3 · rollback() → abort() finds UPDATE op, reads old_value='Bob', calls _raw_update(key=2, old_record) to restore original data.")
        db.rollback(txn)
        _wal_snapshot(db)
        _section("Verification")
        record = db.get_table("users").search(2)
        _result("record['name'] after rollback", record["name"])
        _table_snapshot(db, "users")
        self.assertEqual(record["name"], "Bob")
        _ok("Before-image correctly restored: 'Robert' → 'Bob'.")

    def test_rollback_delete_restores_row(self):
        _banner("ATOMICITY  ·  rollback delete restores the row")
        _section("Setup")
        db = fresh_db()
        db.insert_record("users", 3, {"id": 3, "name": "Carol"})
        _step("Committed row: key=3, name='Carol'.")
        _section("Action: delete key=3, then ROLLBACK")
        _step("Step 1 · transactional_delete() captures BEFORE-IMAGE {'name':'Carol'} as old_value in the WAL DELETE record.")
        _step("Step 2 · _raw_delete() removes the row from records dict AND B+ Tree.")
        txn = db.begin_transaction()
        db.get_table("users").transactional_delete(txn, 3)
        _step(f"         (row temporarily gone: search(3) = {db.get_table('users').search(3)})")
        _step("Step 3 · rollback() → abort() finds DELETE op, reads old_value, calls _raw_insert(key=3, old_record) to re-insert the row.")
        db.rollback(txn)
        _wal_snapshot(db)
        _section("Verification")
        record = db.get_table("users").search(3)
        _result("search(3) after rollback", record,            good=(record is not None))
        _result("record['name']",           record["name"] if record else "—")
        _table_snapshot(db, "users")
        self.assertIsNotNone(record)
        self.assertEqual(record["name"], "Carol")
        _ok("Deleted row fully restored by rollback.")

    def test_multi_op_transaction_rolls_back_completely(self):
        _banner("ATOMICITY  ·  multi-op transaction rolls back ALL ops")
        _section("Setup")
        db = fresh_db()
        db.insert_record("users", 10, {"id": 10, "name": "Dave"})
        _step("Committed row: key=10, name='Dave'.")
        _section("Action: begin txn with 2 ops (insert key=11 + update key=10), ROLLBACK")
        txn   = db.begin_transaction()
        table = db.get_table("users")
        _step("Op 1 · transactional_insert(key=11, name='Eve') → staged in WAL.")
        table.transactional_insert(txn, 11, {"id": 11, "name": "Eve"})
        _step("Op 2 · transactional_update(key=10, name='David') → before-image 'Dave' saved.")
        table.transactional_update(txn, 10, {"id": 10, "name": "David"})
        _step("         In-memory state now: key=10→'David', key=11→'Eve'.")
        _step("ROLLBACK called → abort() processes ops in REVERSE order:")
        _step("  undo Op2 (UPDATE): restore key=10 to 'Dave' via before-image.")
        _step("  undo Op1 (INSERT): delete key=11 (it never should have existed).")
        db.rollback(txn)
        _wal_snapshot(db)
        _section("Verification")
        dave = table.search(10)
        eve  = table.search(11)
        _result("key=10 name after rollback", dave["name"] if dave else "—")
        _result("key=11 exists after rollback", eve, good=(eve is None))
        _table_snapshot(db, "users")
        self.assertEqual(dave["name"], "Dave")
        self.assertIsNone(eve)
        _ok("All 2 operations rolled back correctly — no partial state remains.")

if __name__ == "__main__":
    unittest.main(verbosity=2)